CREATE TABLE [dbo].[FactSales] (
    [FactSalesID]     BIGINT   IDENTITY (1, 1) NOT NULL,
    [OrderID]         INT      NOT NULL,
    [ProductID]       INT      NOT NULL,
    [OrderDateKey]    INT      NOT NULL,
    [RequiredDateKey] INT      NULL,
    [ShippedDateKey]  INT      NULL,
    [CustomerSK]      INT      NOT NULL,
    [EmployeeSK]      INT      NOT NULL,
    [ProductSK]       INT      NOT NULL,
    [ShipperSK]       INT      NULL,
    [ShipLocationSK]  INT      NULL,
    [Quantity]        SMALLINT NOT NULL,
    [UnitPrice]       MONEY    NOT NULL,
    [Discount]        REAL     NOT NULL,
    [GrossAmount]     MONEY    NOT NULL,
    [DiscountAmount]  MONEY    NOT NULL,
    [NetAmount]       MONEY    NOT NULL,
    [FreightAmount]   MONEY    NULL,
    PRIMARY KEY CLUSTERED ([FactSalesID] ASC),
    CONSTRAINT [FK_FactSales_DimCustomer] FOREIGN KEY ([CustomerSK]) REFERENCES [dbo].[DimCustomer] ([CustomerSK]),
    CONSTRAINT [FK_FactSales_DimDate_OrderDate] FOREIGN KEY ([OrderDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactSales_DimDate_RequiredDate] FOREIGN KEY ([RequiredDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactSales_DimDate_ShippedDate] FOREIGN KEY ([ShippedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactSales_DimEmployee] FOREIGN KEY ([EmployeeSK]) REFERENCES [dbo].[DimEmployee] ([EmployeeSK]),
    CONSTRAINT [FK_FactSales_DimProduct] FOREIGN KEY ([ProductSK]) REFERENCES [dbo].[DimProduct] ([ProductSK]),
    CONSTRAINT [FK_FactSales_DimShipLocation] FOREIGN KEY ([ShipLocationSK]) REFERENCES [dbo].[DimShipLocation] ([ShipLocationSK]),
    CONSTRAINT [FK_FactSales_DimShipper] FOREIGN KEY ([ShipperSK]) REFERENCES [dbo].[DimShipper] ([ShipperSK])
);

